### ISSUE TITLE
Duplicate NPM package for freshdesk API nasirbilloo/FreshDeskNode

### ISSUE THREAD

**Issue by maxkoryukov** [nasirbilloo/FreshDeskNode#1]
Hello!

Recently we have published NPM package for Freshdesk API v2. Here is that project: https://github.com/arjunkomath/node-freshdesk-api

I have compared sources of this and that repositories. So, lets improve this package together!
I will be glad to discuss this!

The first important step: **deprecate this package**

The second: make a pull request to the new repository;)

**Comment by maxkoryukov** [comment]
lust a link: maxkoryukov/node-freshdesk-api#1

**Comment by billoonaire** [comment]
Hi Maksim,

I will look into that today. I don't use Freshdesk anymore so for me
personally, that API is useless, so no problem with deprecating it, unless
someone else was using it :)

**Comment by maxkoryukov** [comment]
@nasirbilloo oh, cool. Deprecating on NPM means, that on every new download end-user will get a notice **this package is deprecated bla bla , use this package bla bla**. The old version will be accessible (probably) forever

**Comment by billoonaire** [comment]
done, deprecated it.

**Comment by maxkoryukov** [comment]
closed in favor of #2
